
import discord
from discord.ext import commands
from discord import app_commands
from PIL import Image, ImageDraw, ImageFont
import io
import aiohttp
import asyncio
from datetime import datetime
from main import bot, db

# Try to load fonts, fall back to default if not available
try:
    FONT_LARGE = ImageFont.truetype("arial.ttf", 36)
    FONT_MEDIUM = ImageFont.truetype("arial.ttf", 24)
    FONT_SMALL = ImageFont.truetype("arial.ttf", 18)
    FONT_TINY = ImageFont.truetype("arial.ttf", 14)
except:
    try:
        FONT_LARGE = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 36)
        FONT_MEDIUM = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 24)
        FONT_SMALL = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 18)
        FONT_TINY = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 14)
    except:
        FONT_LARGE = ImageFont.load_default()
        FONT_MEDIUM = ImageFont.load_default()
        FONT_SMALL = ImageFont.load_default()
        FONT_TINY = ImageFont.load_default()

@bot.tree.command(name="profile", description="🎨 Generate a beautiful profile card with stats and pet info")
@app_commands.describe(user="User to generate profile for (optional)")
async def generate_profile_card(interaction: discord.Interaction, user: discord.Member = None):
    await interaction.response.defer()  # This might take a while
    
    target_user = user or interaction.user
    
    try:
        # Create profile card
        profile_buffer = await create_profile_card(target_user, interaction.guild)
        
        file = discord.File(profile_buffer, filename=f"{target_user.display_name}_profile.png")
        
        embed = discord.Embed(
            title=f"🎨 Profile Card Generated",
            description=f"*Here's {target_user.mention}'s beautiful profile card!*",
            color=target_user.color if target_user.color.value != 0 else 0x3498db
        )
        embed.set_footer(text="🌴 Generated by VAAZHA Bot", icon_url=bot.user.display_avatar.url)
        
        await interaction.followup.send(embed=embed, file=file)
        
    except Exception as e:
        print(f"Profile card error: {e}")
        await interaction.followup.send("❌ Failed to generate profile card. Please try again later.", ephemeral=True)

async def create_profile_card(user: discord.Member, guild: discord.Guild) -> io.BytesIO:
    """Create a beautiful profile card using PIL"""
    
    # Card dimensions
    width, height = 800, 600
    
    # Create base image with gradient background
    img = Image.new('RGB', (width, height), color=(50, 50, 50))
    draw = ImageDraw.Draw(img)
    
    # Create gradient background
    for y in range(height):
        color_val = int(50 + (y / height) * 100)
        color = (color_val, color_val // 2, color_val // 3)
        draw.line([(0, y), (width, y)], fill=color)
    
    # Add decorative border
    border_color = (100, 200, 255)
    draw.rectangle([(10, 10), (width-10, height-10)], outline=border_color, width=5)
    
    # Get user avatar
    avatar_size = 120
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(str(user.display_avatar.url)) as resp:
                avatar_data = await resp.read()
        
        avatar_img = Image.open(io.BytesIO(avatar_data))
        avatar_img = avatar_img.resize((avatar_size, avatar_size))
        
        # Create circular mask for avatar
        mask = Image.new('L', (avatar_size, avatar_size), 0)
        mask_draw = ImageDraw.Draw(mask)
        mask_draw.ellipse((0, 0, avatar_size, avatar_size), fill=255)
        
        # Apply circular mask
        avatar_img.putalpha(mask)
        
        # Paste avatar on card
        avatar_x = 50
        avatar_y = 50
        img.paste(avatar_img, (avatar_x, avatar_y), avatar_img)
        
    except Exception as e:
        print(f"Avatar error: {e}")
        # Draw placeholder circle if avatar fails
        draw.ellipse((avatar_x, avatar_y, avatar_x + avatar_size, avatar_y + avatar_size), 
                    fill=(100, 100, 100), outline=border_color, width=3)
    
    # Draw user info
    info_x = avatar_x + avatar_size + 30
    info_y = avatar_y
    
    # Username
    username = user.display_name[:20]  # Limit length
    draw.text((info_x, info_y), username, font=FONT_LARGE, fill=(255, 255, 255))
    
    # Discord tag
    tag = f"#{user.discriminator}" if user.discriminator != "0" else ""
    draw.text((info_x, info_y + 40), f"{user.name}{tag}", font=FONT_SMALL, fill=(150, 150, 150))
    
    # Join date
    join_date = user.joined_at.strftime("%B %d, %Y") if user.joined_at else "Unknown"
    draw.text((info_x, info_y + 70), f"Joined: {join_date}", font=FONT_TINY, fill=(180, 180, 180))
    
    # Get karma data
    karma = 0
    karma_rank = "Unranked"
    if db is not None:
        try:
            karma_data = await db.karma.find_one({
                'user_id': str(user.id),
                'guild_id': str(guild.id)
            })
            if karma_data:
                karma = karma_data.get('karma', 0)
            
            # Get rank
            users_sorted = await db.karma.find({'guild_id': str(guild.id)}).sort('karma', -1).to_list(None)
            rank = next((i + 1 for i, u in enumerate(users_sorted) if u['user_id'] == str(user.id)), len(users_sorted) + 1)
            karma_rank = f"#{rank}"
        except:
            pass
    
    # Karma section
    karma_y = 220
    draw.text((50, karma_y), "🌟 KARMA STATS", font=FONT_MEDIUM, fill=(255, 215, 0))
    
    # Karma points
    draw.text((50, karma_y + 40), f"Points: {karma}", font=FONT_SMALL, fill=(255, 255, 255))
    draw.text((200, karma_y + 40), f"Rank: {karma_rank}", font=FONT_SMALL, fill=(255, 255, 255))
    
    # Karma progress bar
    progress_width = 300
    progress_height = 20
    progress_x = 50
    progress_y = karma_y + 70
    
    # Background bar
    draw.rectangle([(progress_x, progress_y), (progress_x + progress_width, progress_y + progress_height)], 
                  fill=(50, 50, 50), outline=(100, 100, 100))
    
    # Progress fill (next milestone is every 5 karma)
    if karma > 0:
        next_milestone = ((karma // 5) + 1) * 5
        progress = (karma % 5) / 5
        fill_width = int(progress_width * progress)
        draw.rectangle([(progress_x, progress_y), (progress_x + fill_width, progress_y + progress_height)], 
                      fill=(0, 255, 100))
        
        # Progress text
        draw.text((progress_x + progress_width + 10, progress_y), f"{karma % 5}/5 to {next_milestone}", 
                 font=FONT_TINY, fill=(200, 200, 200))
    
    # Pet section
    pet_y = 350
    draw.text((50, pet_y), "🐾 PET COMPANION", font=FONT_MEDIUM, fill=(255, 100, 150))
    
    pet_info = "No pet adopted"
    pet_details = "Use /adoptpet <name> to get started!"
    
    if db is not None:
        try:
            pet_data = await db.pets.find_one({
                'user_id': str(user.id),
                'guild_id': str(guild.id)
            })
            if pet_data:
                pet_name = pet_data.get('pet_name', 'Unknown')
                pet_level = pet_data.get('pet_level', 1)
                pet_xp = pet_data.get('pet_xp', 0)
                
                # Pet stages
                stages = {1: "Baby", 2: "Toddler", 3: "Young", 4: "Teen", 5: "Adult",
                         6: "Mature", 7: "Elder", 8: "Ancient", 9: "Legendary", 10: "Mythical"}
                stage = stages.get(pet_level, "Transcendent")
                
                pet_info = f"{pet_name} - Level {pet_level} {stage}"
                pet_details = f"XP: {pet_xp} | Messages: {pet_data.get('messages_sent', 0):,}"
        except:
            pass
    
    draw.text((50, pet_y + 40), pet_info, font=FONT_SMALL, fill=(255, 255, 255))
    draw.text((50, pet_y + 65), pet_details, font=FONT_TINY, fill=(180, 180, 180))
    
    # Roles section
    roles_y = 450
    draw.text((50, roles_y), "🎭 ROLES", font=FONT_MEDIUM, fill=(150, 100, 255))
    
    # Get top 3 roles (excluding @everyone)
    user_roles = [role.name for role in user.roles if role.name != "@everyone"][-3:]
    if user_roles:
        roles_text = " • ".join(user_roles)
        if len(roles_text) > 50:
            roles_text = roles_text[:47] + "..."
    else:
        roles_text = "No special roles"
    
    draw.text((50, roles_y + 40), roles_text, font=FONT_SMALL, fill=(200, 200, 200))
    
    # Additional stats
    stats_y = 520
    draw.text((50, stats_y), f"Total Roles: {len(user.roles) - 1} | Status: {str(user.status).title()}", 
             font=FONT_TINY, fill=(150, 150, 150))
    
    # Add decorative elements
    # Corner decorations
    corner_size = 30
    draw.polygon([(width-40, 20), (width-20, 20), (width-20, 40)], fill=border_color)
    draw.polygon([(20, height-40), (20, height-20), (40, height-20)], fill=border_color)
    
    # Footer
    draw.text((width-200, height-30), "🌴 VAAZHA Bot", font=FONT_TINY, fill=(100, 200, 255))
    
    # Convert to bytes
    buffer = io.BytesIO()
    img.save(buffer, format='PNG', quality=95)
    buffer.seek(0)
    
    return buffer

@bot.tree.command(name="profilesetup", description="🎨 Customize your profile card background")
@app_commands.describe(
    background="Choose background style",
    color="Custom color for background (hex code like #FF5733)"
)
@app_commands.choices(background=[
    app_commands.Choice(name="Dark Blue Gradient", value="dark_blue"),
    app_commands.Choice(name="Purple Galaxy", value="purple"),
    app_commands.Choice(name="Green Forest", value="green"),
    app_commands.Choice(name="Orange Sunset", value="orange"),
    app_commands.Choice(name="Red Fire", value="red"),
    app_commands.Choice(name="Custom Color", value="custom")
])
async def profile_setup(interaction: discord.Interaction, background: str, color: str = None):
    if db is None:
        await interaction.response.send_message("❌ Database not connected!", ephemeral=True)
        return
    
    # Validate custom color
    if background == "custom":
        if not color:
            await interaction.response.send_message("❌ Please provide a hex color code (like #FF5733) for custom background!", ephemeral=True)
            return
        
        # Validate hex color
        if not color.startswith('#') or len(color) != 7:
            await interaction.response.send_message("❌ Invalid hex color! Use format like #FF5733", ephemeral=True)
            return
        
        try:
            int(color[1:], 16)  # Test if it's valid hex
        except ValueError:
            await interaction.response.send_message("❌ Invalid hex color! Use format like #FF5733", ephemeral=True)
            return
    
    # Save profile customization
    profile_data = {
        'user_id': str(interaction.user.id),
        'guild_id': str(interaction.guild.id),
        'background_style': background,
        'custom_color': color,
        'updated_at': datetime.utcnow()
    }
    
    await db.profile_customization.update_one(
        {'user_id': str(interaction.user.id), 'guild_id': str(interaction.guild.id)},
        {'$set': profile_data},
        upsert=True
    )
    
    embed = discord.Embed(
        title="🎨 Profile Customized!",
        description=f"**Background:** {background}\n" + (f"**Color:** {color}" if color else "") + "\n\nUse `/profile` to see your new customized profile card!",
        color=0x43b581
    )
    if color:
        try:
            embed.color = int(color[1:], 16)  # Set embed color to match custom color
        except:
            pass
    
    await interaction.response.send_message(embed=embed)
